import json
import os

OUTER_FILE_DATA = """import * as THREE from "three";

// this is auto generated by scripts/read_path.py
// i'm using this tutorial to get points from blender path 
// https://www.youtube.com/watch?v=58k6PLYnOuI&t=253s
// which provides all pts in a json file, but i cannot afford to read 10+ json files 
// so the script allows me to essentially hardcode these values 

export const paths = {
"""
INPUT_DIRECTORY = "" # add input directory path (i.e, public/paths/)
OUTPUT_FILE = "" # add output file path (i.e, paths.ts)

def read_json(path: str):
    file = open(path, "r")
    return json.load(file)

def parse_path_helper(name, file):
    output = ""

    output += f"\t\"{name}\": new THREE.CatmullRomCurve3([\n"
    for pt in file["points"]:
        x, y, z = pt["x"], pt["y"], pt["z"]
        output += f"\t\tnew THREE.Vector3({x}, {y}, {z}),\n"
    output += "\t]),\n"

    return output

def parse_path(filename, filepath):
    data = read_json(filepath)
    output = parse_path_helper(filename, data)
    return output

def main():
    output = ""
    output += OUTER_FILE_DATA
    
    for file in os.listdir(INPUT_DIRECTORY):
        if file.endswith(".json"):
            input_file = os.path.join(INPUT_DIRECTORY, file)
            output += parse_path(file[:-5], input_file)
    
    output += "};"

    with open(OUTPUT_FILE, "w") as file:
        file.write(output)

if __name__ == "__main__":
    main()